### ISSUE TITLE
Exception lib usage in Fragment

### ISSUE THREAD

**Issue by zhambylgaziz** [bmc08gt/scrcast#59]
**Describe the bug**
It is a runtime exception when attempted to create instance of ScrCast about lifecycle.

 java.lang.IllegalStateException: LifecycleOwner y@d1a71e8 is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.

**Expected behavior**
Expected creation of ScrCast and later start recording.

**To Reproduce**
Try to create instance of class in fragment (no matter onCreate, onActivityCreated, onViewCreate)

**Logs/Screenshots**
![image](https://user-images.githubusercontent.com/37974317/156334567-20b37008-1a75-414d-9d4f-ec3b0a63e599.png)
![image](https://user-images.githubusercontent.com/37974317/156334371-7308a345-3703-4b7f-b719-85084731a610.png)

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: kz.nurbank.app.dev, PID: 32114
    java.lang.IllegalStateException: LifecycleOwner kz.crystalspring.ib_for_individuals.ui.activities.client_restrictions.ClientRestrictionsActivity@d1a71e8 is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.
        at androidx.activity.result.ActivityResultRegistry.register(ActivityResultRegistry.java:123)
        at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.java:659)
        at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.java:668)
        at dev.bmcreations.scrcast.ScrCast.<init>(ScrCast.kt:166)
        at dev.bmcreations.scrcast.ScrCast.<init>(ScrCast.kt:42)
        at dev.bmcreations.scrcast.ScrCast$Companion.use(ScrCast.kt:375)
        at kz.crystalspring.ib_for_individuals.ui.accounts.accounts_binding.form.photo.face.ContactOperationFaceFragment.onCreate(ContactOperationFaceFragment.kt:86)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8061)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Version**
minSdk: 23
targetSdk: 30
libraryVersion: 0.3.0

**Comment by eric-ampire** [comment]
Any update about this issue @zhambylgaziz

**Comment by eric-ampire** [comment]
I thing the exception is triggered by this code

```kotlin
private val startRecording = activity.registerForActivityResult(RecordScreen()) { result ->
    if (result.resultCode == Activity.RESULT_OK) {
        if (options.moveTaskToBack) activity.moveTaskToBack(true)
        val output = outputFile
        if (output != null) {
            startService(result, output)
        }
    }
}
```
